name: ci
on: push
jobs:
  lint-server:
    name: lint-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5
          cache: 'npm'
      - run: npm ci
      - run: npm run lint --workspace=server

  lint-client:
    name: lint-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5
          cache: 'npm'
      - run: npm ci
      - run: npm run lint --workspace=client

  test-server:
    name: test-server
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:8.0
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5
          cache: 'npm'
      - run: npm ci
      - run: npm run test --workspace=server
        env:
          NODE_ENV: test